# Generated by Django 4.1.7 on 2023-03-19 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=180)),
                ('prop_type', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=180)),
                ('rooms', models.IntegerField()),
                ('baths', models.IntegerField()),
                ('parking', models.IntegerField()),
                ('max_guests', models.IntegerField()),
                ('is_available', models.BooleanField(default=True)),
                ('first_day_available', models.DateTimeField(auto_now=True)),
                ('rate', models.IntegerField()),
                ('owner', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateTimeField()),
                ('check_out', models.DateTimeField()),
                ('num_days', models.IntegerField()),
                ('numGuests', models.IntegerField()),
                ('property_id', models.IntegerField()),
                ('customer_id', models.IntegerField()),
                ('owner_id', models.IntegerField()),
                ('status', models.CharField(max_length=180)),
            ],
        ),
    ]
